interface Props {
  autonomy: number
  onAsk: (q: string) => void
  onViewAudit: () => void
}

const agentActions = [
  { text: '내일 미사 시간 캘린더에 추가됨', time: '2분 전', active: false },
  { text: '사순 묵상 자료 준비 중...', time: '진행중', active: true },
  { text: '성경 읽기 진도 78% 분석 완료', time: '1시간 전', active: false },
]

const anticipatory = [
  {
    title: '저녁기도 시간입니다',
    desc: '성무일도 저녁기도 (만과)',
    trigger: '매일 18:30 기도 습관 감지',
    confidence: 96,
    action: '시작하기',
    gradient: 'from-violet-500/10 to-indigo-500/10',
    border: 'border-violet-200/50',
  },
  {
    title: '내일 복음 미리보기',
    desc: '마르 10,28-31 "백 배로 받을 것"',
    trigger: '저녁마다 다음날 독서 확인 패턴',
    confidence: 89,
    action: '해설 보기',
    gradient: 'from-blue-500/10 to-cyan-500/10',
    border: 'border-blue-200/50',
  },
  {
    title: '묵주기도 리마인더',
    desc: '오늘 아직 봉헌하지 않았습니다',
    trigger: '매일 1단 봉헌 목표 설정됨',
    confidence: 100,
    action: '봉헌하기',
    gradient: 'from-amber-500/10 to-orange-500/10',
    border: 'border-amber-200/50',
  },
]

const delegations = [
  { task: '매일 아침 복음 요약', freq: '07:00', active: true },
  { task: '묵주기도 봉헌 리마인더', freq: '21:00', active: true },
  { task: '본당 공지사항 모니터링', freq: '실시간', active: true },
  { task: '성경 읽기 진도 추적', freq: '매주 월', active: false },
]

export function Phase2Home({ autonomy, onAsk, onViewAudit }: Props) {
  return (
    <main className="max-w-2xl mx-auto px-5 pb-24 md:pb-8 pt-6 md:pt-10">
      {/* Agent Status */}
      <section className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75" />
            <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500" />
          </span>
          <span className="text-[10px] text-indigo-500 font-medium">에이전트 활성</span>
          <span className="text-[10px] text-black/20">· 자율도: {['최소', '낮음', '균형', '높음', '최대'][autonomy]}</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-semibold tracking-tight">안녕하세요, 마리아님</h1>
        <p className="text-black/30 text-xs mt-1">연중 제8주간 월요일 · 2026년 3월 3일</p>
      </section>

      {/* Agent Activity Strip */}
      <section className="mb-8">
        <button onClick={onViewAudit} className="flex items-center gap-2 mb-2 group">
          <h2 className="text-[11px] text-black/30 tracking-wider uppercase">에이전트 활동</h2>
          <span className="text-[10px] text-indigo-500 opacity-0 group-hover:opacity-100 transition-opacity">전체 보기 →</span>
        </button>
        <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">
          {agentActions.map(a => (
            <div key={a.text} className={`shrink-0 flex items-center gap-2 bg-white rounded-xl px-3 py-2 border transition-colors ${a.active ? 'border-indigo-200 bg-indigo-50/50' : 'border-black/5'}`}>
              <span className={`text-[10px] ${a.active ? 'text-indigo-500 animate-pulse' : 'text-green-500'}`}>{a.active ? '⟳' : '✓'}</span>
              <span className="text-[11px] text-black/50 whitespace-nowrap">{a.text}</span>
              <span className="text-[9px] text-black/20 whitespace-nowrap">{a.time}</span>
            </div>
          ))}
        </div>
      </section>

      {/* The Input */}
      <section className="mb-10">
        <button
          onClick={() => onAsk('')}
          className="w-full bg-white rounded-2xl p-4 flex items-center gap-3 shadow-[0_1px_4px_rgba(0,0,0,0.03)] border border-black/5 hover:border-indigo-300/50 hover:shadow-[0_4px_20px_rgba(99,102,241,0.08)] transition-all active:scale-[0.99]"
        >
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center shrink-0">
            <span className="text-white text-sm">✦</span>
          </div>
          <span className="text-black/25 text-sm text-left">질문하거나 작업을 위임하세요...</span>
        </button>
      </section>

      {/* Anticipatory Cards (Generated by AI) */}
      <section className="mb-10">
        <h2 className="text-[11px] text-black/30 tracking-wider uppercase mb-3">
          <span className="text-indigo-500">✦</span> AI가 준비한 항목
          <span className="text-[9px] text-black/15 ml-2 normal-case">Generative UI · Anticipatory Design</span>
        </h2>
        <div className="space-y-3">
          {anticipatory.map(card => (
            <div key={card.title} className={`bg-gradient-to-r ${card.gradient} rounded-2xl p-4 border ${card.border}`}>
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <div className="font-medium text-sm">{card.title}</div>
                  <div className="text-xs text-black/50 mt-0.5">{card.desc}</div>
                  <span className="inline-block text-[9px] text-indigo-500/70 bg-indigo-500/5 px-2 py-0.5 rounded-full mt-2">
                    💡 {card.trigger}
                  </span>
                </div>
                <div className="text-right shrink-0">
                  <div className="flex items-center gap-1 mb-2">
                    <div className="w-8 h-1 rounded-full bg-black/5 overflow-hidden">
                      <div className={`h-full rounded-full ${card.confidence >= 90 ? 'bg-green-500' : 'bg-amber-500'}`} style={{ width: `${card.confidence}%` }} />
                    </div>
                    <span className="text-[9px] text-black/30">{card.confidence}%</span>
                  </div>
                  <button onClick={() => onAsk(card.title)} className="text-[11px] text-indigo-600 font-medium hover:underline">
                    {card.action} →
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Delegated Tasks */}
      <section className="mb-10">
        <h2 className="text-[11px] text-black/30 tracking-wider uppercase mb-3">
          위임된 작업 <span className="text-[9px] text-black/15 ml-2 normal-case">Delegative UI</span>
        </h2>
        <div className="bg-white rounded-2xl border border-black/5 divide-y divide-black/5">
          {delegations.map(d => (
            <div key={d.task} className="flex items-center gap-3 px-4 py-3">
              <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${d.active ? 'bg-green-500' : 'bg-black/10'}`} />
              <div className="flex-1 min-w-0">
                <div className="text-sm truncate">{d.task}</div>
                <div className="text-[10px] text-black/25">{d.freq}</div>
              </div>
              <button className="text-[10px] text-black/20 hover:text-red-400 transition-colors shrink-0">
                {d.active ? '중지' : '시작'}
              </button>
            </div>
          ))}
          <button onClick={() => onAsk('새 작업 위임')} className="w-full px-4 py-3 text-left text-xs text-indigo-500 hover:bg-indigo-50/50 transition-colors rounded-b-2xl">
            + 새 작업 위임하기
          </button>
        </div>
      </section>

      {/* Concept Tags */}
      <section className="text-center py-4">
        <div className="inline-flex items-center gap-2 text-[10px] text-black/15 flex-wrap justify-center">
          {['Generative UI', 'Autonomy Dial', 'Anticipatory', 'Delegative', 'MCP', 'A2A'].map((t, i) => (
            <span key={t} className="flex items-center gap-2">
              {i > 0 && <span className="w-0.5 h-0.5 rounded-full bg-black/10" />}
              {t}
            </span>
          ))}
        </div>
      </section>
    </main>
  )
}
